name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  realese:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
    - uses: actions/checkout@master

#    - name: Login to Docker Hub
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DOCKER_HUB_USERNAME }}
#        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
#      id: buildx
#      uses: docker/setup-buildx-action@v1
      run: |
        cd ./linaro
        docker build --rm --force-rm -t armada8040:linaro_gcc . --file dockerfile --tag my-image-name:$(date +%s)

#    - name: Build the Docker image and push
#      id: docker_build
#      uses: docker/build-push-action@v2
#      with:
#        context: ./linaro
#        file: ./dockerfile
#        push: false
#        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/armada8040:linaro_gcc

        #docker build --rm --force-rm -t armada8040:linaro_gcc . --file dockerfile --tag my-image-name:$(date +%s)
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
